### ISSUE TITLE
Downloading a read-only file via python client gives irods.exception.CAT_NO_ACCESS_PERMISSION: failed to set access time for [file]

### ISSUE THREAD

**Issue by RubenGarcia** [irods/irods_capability_storage_tiering#175]
- [x] main
- [x] 4-3-stable
---
Downloading a read-only file via python client gives 
irods.exception.CAT_NO_ACCESS_PERMISSION: failed to set access time for [file]
due to storage tiering trying to update the access time.
See https://github.com/irods/python-irodsclient/issues/320
for details.
If the access time is not updated, the logic for tiering won't work correctly.
The issue will probably also exist when using iget (and iget may be masking the error).

**Comment by trel** [comment]
Also hit this when replicating another user's data object with admin rights.

`irepl -M ../alice/alicetier`

```
Jan 20 08:09:14 pid:17701 NOTICE: _rsGenQuery: genQuery status = -818000
Jan 20 08:09:14 pid:17701 NOTICE: rsGenQuery: _rsGenQuery failed, status = -818000
Jan 20 08:09:14 pid:17701 NOTICE: getDataObjInfo: rsGenQuery error, status = -818000
Jan 20 08:09:14 pid:17701 NOTICE: checkAndGetObjectId cmlExecuteNoAnswerSql(rollback) succeeded
Jan 20 08:09:14 pid:17701 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
Jan 20 08:09:14 pid:17701 remote addresses: 127.0.0.1, ::1 ERROR: iRODS Exception:
    file: /irods_plugin/libirods_rule_engine_plugin-apply_access_time.cpp
    function: void (anonymous namespace)::update_access_time_for_data_object(rsComm_t *, const std::string &, const std::string &)
    line: 36
    code: -818000 (CAT_NO_ACCESS_PERMISSION)
    message:
        failed to set access time for [/tempZone/home/alice/alicetier]
```

**Comment by alanking** [comment]
> Also hit this when replicating another user's data object with admin rights.
>
> irepl -M ../alice/alicetier

I was not able to reproduce this on 4.3.3 with the 4.3.3.0 plugin.

I also tried running this rule to open/read/close the object:
```bash
$ cat ~/.irods/irods_environment.json | grep user
    "irods_user_name": "alan",
$ ils -AL ../public/foo
  rods              0 demoResc          284 2025-01-13.19:03 & foo
        generic    /var/lib/irods/Vault/home/public/foo
        ACL - alan#tempZone:read_object   
$ cat /open.r 
main() {
        *len = 284
        *path = "/tempZone/home/public/foo"
        msiDataObjOpen("objPath=*path++++openFlags=O_RDONLY", *fd);
        msiDataObjRead(*fd, *len, *out);
        msiDataObjClose(*fd, *err);
        writeLine("stdout", "*out");
}
INPUT null
OUTPUT ruleExecOut
$ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F open.r
#!/bin/sh
#
# Control the iRODS servers.
#
# Usage is:
#       irodsctl [args] [options]
#
# Type 'irodsctl --help' for a list of options.
#
# This shell script runs the 'irods_control' Python script.
#
IRODS_HOME=$(dirname $0)
python3 $IRODS_HOME/scripts/irods_control.py $*
exit $?

```
The access_time metadata was not affected.

And `iget` works as expected, as reported here and in #203. I haven't tried PRC but I imagine it would function much like the native rule that I wrote above.

I'm going to say that this just needs a test and we can call it resolved.

**Comment by trel** [comment]
Seems a correct assessment to me.

**Comment by alanking** [comment]
Actually... this isn't exactly the same thing. The rule would be run completely in the server and therefore wouldn't trigger any PEPs. I tried again with PRC and was able to reproduce the issue with 4.3.3 and 4.3.3.0 plugin:
```python
>>> from irods.test.helpers import make_session
>>> ses = make_session()
>>> ses.data_objects.get("/tempZone/home/public/foo", "/tmp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/irods/manager/data_object_manager.py", line 280, in get
    self._download(
  File "/usr/local/lib/python3.12/dist-packages/irods/manager/data_object_manager.py", line 241, in _download
    with self.open(
  File "/usr/local/lib/python3.12/dist-packages/irods/data_object.py", line 205, in close
    self.conn.close_file(self.desc, **self.options)
  File "/usr/local/lib/python3.12/dist-packages/irods/connection.py", line 742, in close_file
    self.recv()
  File "/usr/local/lib/python3.12/dist-packages/irods/connection.py", line 181, in recv
    raise exc
irods.exception.CAT_NO_ACCESS_PERMISSION: failed to set access time for [/tempZone/home/public/foo]
```
(taken from https://github.com/irods/python-irodsclient/issues/320#issuecomment-983260490)

Sorry about the label churn...

**Comment by alanking** [comment]
Writing a test for this with our existing tooling is going to be difficult because we probably shouldn't introduce any additional clients as dependencies in the tests, and none of the iCommands will serve the open/read/close purpose. We may have to address #200 in part before this is complete by implementing PEPs for `replica_open` and `replica_close` APIs. Might as well implement the `get` API PEP as well, which is not currently implemented to update access_time (which is why `iget` does not demonstrate the reported issue).

**Comment by alanking** [comment]
After some discussion we have decided to develop a small test application to exercise the appropriate PEPs for testing. Implementing the other PEPs can happen at another time.
