### ISSUE TITLE
`test_put_multi_fetch_page` fails frequently against Ubuntu 24.04 / MySQL 8.4

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_capability_storage_tiering#279]
- [ ] main
- [ ] 4-3-stable
---
## Bug Report

Encountered during testing of what will be iRODS 4.3.3.
Platform is Ubuntu 24.04.
Database is MySQL 8.4.

The test fails due to the following assertion.

https://github.com/irods/irods_capability_storage_tiering/blob/822347c9dc05612e53e6eb2e1da473283ee675f1/packaging/test_plugin_unified_storage_tiering.py#L1520

The test creates (256 * 2) + 1 data objects and then starts waiting for them to be moved to another tier. This works, but close observation shows there are failures which lead to stale replicas existing on the original tier. I've noticed at least 3 replicas in this state following test completion. The test fails because it finds replicas on the original tier, even though it moved 400+ replicas.

Decreasing the number of replicas involved (by 100 or so) resulted in the test passing. However, reducing the number of replicas isn't a real fix. We need to figure out **WHY** data movement fails for some replicas.

Below is the output of the failed test.

```
        <testcase classname="irods.test.test_plugin_unified_storage_tiering.TestStorageTieringContinueInxMigration" name="test_put_multi_fetch_page" time="287.555" timestamp="2024-08-13T21:11:55" file="scripts/irods/test/test_plugin_unified_storage_tiering.py" line="1503">
                <failure type="AssertionError" message=""><![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_plugin_unified_storage_tiering.py", line 180, in delay_assert
    out, err, rc = function()
                   ^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/test_plugin_unified_storage_tiering.py", line 1520, in <lambda>
    delay_assert(lambda: admin_session.assert_icommand_fail(['ils', '-l', dirname], 'STDOUT_SINGLELINE', 'ufs0'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/session.py", line 166, in assert_icommand_fail
    return assert_command_fail(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/command.py", line 79, in assert_command_fail
    return _assert_helper(*args, should_fail=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
           ^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_plugin_unified_storage_tiering.py", line 1520, in test_put_multi_fetch_page
    delay_assert(lambda: admin_session.assert_icommand_fail(['ils', '-l', dirname], 'STDOUT_SINGLELINE', 'ufs0'))
  File "/var/lib/irods/scripts/irods/test/test_plugin_unified_storage_tiering.py", line 187, in delay_assert
    assert(False)
           ^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_plugin_unified_storage_tiering.py", line 1526, in test_put_multi_fetch_page
    admin_session.assert_icommand('irm -r ' + dirname)
  File "/var/lib/irods/scripts/irods/test/session.py", line 162, in assert_icommand
    return assert_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/command.py", line 76, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
           ^^^^^^
AssertionError
]]></failure>
```

Here is the final listing before the assertion fails.
```
id     name
11110 {"delay_conditions":"<INST_NAME>irods_rule_engine_plugin-unified_storage_tiering-instance</INST_NAME><EF>60s REPEAT UNTIL SUCCESS OR 5 TIMES</EF><PLUSET>1s</PLUSET>","destination-resource":"ufs1","group-name":"example_group","md5":"ca0e41ba44e21e0c2e4eb7d9064d0caf","object-path":"/tempZone/home/rods/test_put_multi_fetch_page/junk0365","preserve-replicas":false,"rule-
engine-instance-name":"irods_rule_engine_plugin-unified_storage_tiering-instance","rule-engine-operation":"irods_policy_data_movement","source-replica-number":"0","source-resource":"ufs0","user-name":"rods","user-zone":"tempZone","verification-type":"catalog"}

 --- IrodsSession: icommand executed by [rods#tempZone] [ils -l test_put_multi_fetch_page] ---
Assert FAIL Command: ils -l test_put_multi_fetch_page
Expecting STDOUT_SINGLELINE: ['ufs0']
  stdout:
    | /tempZone/home/rods/test_put_multi_fetch_page:
<snip>
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0360
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0361
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0362
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0363
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0364
    |   rods              0 ufs0            1 2024-08-14.15:30 & junk0365  <== Should not see ufs0.
    |   rods              1 ufs1            1 2024-08-14.15:32 X junk0365  <== Or a stale replica.
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0366
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0367
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0368
    |   rods              1 ufs1            1 2024-08-14.15:32 & junk0369
<snip>
```

**Comment by alanking** [comment]
While this is not the same failure as #246, it is in the same test class as that failure, so I'm going to link them as possibly related...

**Comment by alanking** [comment]
Forgot to include this in previous comment... Found the place in the logs where the unlink failed for this data object:
```
[-]    /irods_source/server/api/src/rsFileUnlink.cpp:112:int _rsFileUnlink(rsComm_t *, fileUnlinkInp_t *) :  status [UNIX_FILE_UNLINK_ERR]  errno [No such file or directory] -- message [fileRead failed for [/tmp/irods/ufs1/home/rods/test_put_multi_fetch_page/junk0474]-515002]
    [-] /irods_source/server/drivers/src/fileDriver.cpp:197:irods::error fileUnlink(rsComm_t *, irods::first_class_object_ptr) :  status [UNIX_FILE_UNLINK_ERR]  errno [No such file or directory] -- message [failed to call unlink]
        [-] /irods_source/plugins/resources/unixfilesystem/src/unixfilesystem.cpp:828:irods::error unix_file_unlink(irods::plugin_context &) :  status [UNIX_FILE_UNLINK_ERR]  errno [No such file or directory] -- message [Unlink error for file: "/tmp/irods/ufs1/home/rods/test_put_multi_fetch_page/junk0474", errno = "No such file or directory", status = -515002.]
```
```
"[dataObjUnlinkS:610] - failed to physically unlink replica [error_code=[-515002], path=[/tempZone/home/rods/test_put_multi_fetch_page/junk0474], hierarchy=[ufs1]"
```
Things are still fuzzy, but I'm seeing a few things now.

First, the "Function sequence error" is *likely* a problem similar (but not necessarily identical) to https://github.com/irods/irods/issues/7440. I will need to try building against 4-3-stable to see if that changes the issue from the database error to an iRODS error (preferable, but not the solution to this issue).

The cause behind these database errors is still unclear. My initial thought was that multiple delay rule executors were picking up the rule at the same time and multiple replications were happening as a result. My suspicion is this "transaction isolation level" that we have to mess with for MySQL in the testing environment and elsewhere: https://github.com/irods/irods_testing_environment/blob/56e7c810dc6fbbfc9f0ccd139119314b8c3c6cb5/projects/ubuntu-24.04/ubuntu-24.04-mysql-8.4/docker-compose.yml#L4-L39

However, we don't see this failure for other databases. I tried running the test against Postgres 16 and carefully watched the logs. While I saw many messages about delay rules not existing...
```
"Could not find a delay rule with id [12637]."
"Could not get delay rule information [rule id=[12637]]"
"dequeueing rule because rule ID [12637] no longer exists in the catalog"
```
I did not see any errors about failure to replicate.

I tried running the test a few times on MySQL 8.0 and did not see the failure. I did see the failure to replicate, but no failure in the test itself, and no failures to trim afterwards.

Finally, I added some logging statements using the new logger (e.g. `irods::experimental::log::rule_engine`) and they're not showing up, despite calls to `rodsLog` working. So, something is wrong there, too.

Investigation ongoing.

**Comment by alanking** [comment]
I think this failure is not related to storage tiering. I was able to reproduce with a native rule language rule: https://github.com/irods/irods/issues/8154 I don't think we will be able to fix this in 4.3.3.1 as the issue exists in the core server (either in the delay server or the replication API or the database plugin).

**Comment by alanking** [comment]
Removing from the 4.3.3.1 milestone as this issue is not related to storage tiering. We can circle back to this once https://github.com/irods/irods/issues/8154 is resolved.
